### ISSUE TITLE
http://btoe.ws/ is broken

### ISSUE THREAD

**Issue by IonicaBizau** [btoews/mastahyeti.info#1]
A nice GitHub Pages 404 error appears

![screenshot from 2015-04-08 11 33 42](https://cloud.githubusercontent.com/assets/2864371/7041573/22580984-dde3-11e4-88cb-4a1488e43fd8.png)

**Comment by btoews** [comment]
Thanks. I intentionally took this site down.

**Comment by IonicaBizau** [comment]
@mastahyeti Then you have to update your GitHub profile.

BTW, you [resemble a friend who is athlete](http://alergpentruocauza.ro/wp-content/uploads/2013/05/971825_570577836316011_474347337_n.jpg). :runner: I built [his website](http://alergpentruocauza.ro/). :smile:

**Comment by btoews** [comment]
:smile:

**Comment by IonicaBizau** [comment]
By _updating your GitHub profile_ I mean to update your website:

![screenshot from 2015-04-08 19 08 56](https://cloud.githubusercontent.com/assets/2864371/7049493/c044e2b8-de22-11e4-9c36-2748a9c2885c.png)

**Comment by btoews** [comment]
Yep. I figured that was what you meant.
